CREATE TABLE flights_raw (
    year INT,
    month INT,
    day_of_month INT,
    day_of_week INT,
    flight_date DATE,
    carrier_code VARCHAR(10),
    flight_number INT,
    origin VARCHAR(5),
    destination VARCHAR(5),
    scheduled_dep_time INT,
    actual_dep_time INT,
    dep_delay FLOAT,
    scheduled_arr_time INT,
    actual_arr_time INT,
    arr_delay FLOAT,
    cancelled BIT,
    cancellation_code VARCHAR(5),
    diverted BIT,
    distance FLOAT,
    carrier_delay FLOAT,
    weather_delay FLOAT,
    nas_delay FLOAT,
    security_delay FLOAT,
    late_aircraft_delay FLOAT
);
